### ISSUE TITLE
Feature Request: Mitigation

### ISSUE THREAD

**Issue by GabbzGit** [worldygit/worldy-rotation#3]
Mitigation feature where we define spells, buffs, debuffs etc where a player should considere to proactively should use a self mitigation ability such as RuneTap or similiar.

The function should return true if there is something that needs to be mitigated and also some sort of type, ie Magic, Physical, Poison etc so that appriopiat ability can be used.

The function should loop through all current enemies(nameplates?) and identify if the player is target or impacted. 

Things to consider: Could be target the player(self mitigation), another target(external mitigation) or groupwide(self mitigation, party external). 

Last boss Plaguefall for example is a self and group based scenario for mitigation, First, Second and Thirdboss in SD is another.

**Comment by worldygit** [comment]
For this purpose there exists `Player:ActiveMitigationNeeded()` in the HeroLib aswell as `Commons.ShouldMitigate()` in the WorldyRotations `Commons.lua`. SpellIDs of mitigatable spells could be added to `Commons.MitigateIDs`. 

Furthermore there exists `Commons.GetTimer(spellId)` with that method someone can grab the BigWigs/LittleWigs Timer of a certain spell.
